// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYRH4e17zNTGmXQgSNMiXRimiL-rHH5vY',
    appId: '1:200347648452:web:ca12b6f83464e393c9e491',
    messagingSenderId: '200347648452',
    projectId: 'catalogo-peliculas-ce096',
    authDomain: 'catalogo-peliculas-ce096.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-ce096.firebasestorage.app',
    measurementId: 'G-00ZCBS5X8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZeUq18YUr3zEZcAusTI3MDsshXiq6fCo',
    appId: '1:200347648452:android:e68009ea0a765387c9e491',
    messagingSenderId: '200347648452',
    projectId: 'catalogo-peliculas-ce096',
    storageBucket: 'catalogo-peliculas-ce096.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi8fJnA5s3vWzt4fYXnyiZOKqD1Hh5mEU',
    appId: '1:200347648452:ios:6a12844ef7695904c9e491',
    messagingSenderId: '200347648452',
    projectId: 'catalogo-peliculas-ce096',
    storageBucket: 'catalogo-peliculas-ce096.firebasestorage.app',
    iosBundleId: 'com.example.catalogoPeliculas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi8fJnA5s3vWzt4fYXnyiZOKqD1Hh5mEU',
    appId: '1:200347648452:ios:6a12844ef7695904c9e491',
    messagingSenderId: '200347648452',
    projectId: 'catalogo-peliculas-ce096',
    storageBucket: 'catalogo-peliculas-ce096.firebasestorage.app',
    iosBundleId: 'com.example.catalogoPeliculas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYRH4e17zNTGmXQgSNMiXRimiL-rHH5vY',
    appId: '1:200347648452:web:9073d530b9364696c9e491',
    messagingSenderId: '200347648452',
    projectId: 'catalogo-peliculas-ce096',
    authDomain: 'catalogo-peliculas-ce096.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-ce096.firebasestorage.app',
    measurementId: 'G-4KKWFX3FMB',
  );
}
